apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "airflow"
resources:
 - "namespace.yaml"


helmCharts:
- name: airflow
  repo: https://airflow.apache.org
  namespace: "airflow"
  releaseName: "airflow"
  valuesInline: 
    extraEnv: |
      - name: AIRFLOW__CORE__LOAD_EXAMPLES
        value: 'True'

