- hosts:
  - localhost
  tasks:

    - name: change to kustomize file directory for metallb
      shell: |
               cd ../kustomize/metallb
               kustomize build .   --enable-helm |kubectl apply -f -

    - name: wait for pods to come up
      shell: kubectl get pods -o json
      register: kubectl_get_pods
      until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
      retries: 10
      delay: 30
