- hosts: 
  - k8s-nfsserver0
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: lxd

  tasks:
      - name: install nfs-server
        shell: |
                sudo apt update -qq && sudo apt install -qq -y  nfs-server


      - name: mount nfs_source drive to   shared file path inside container 
        shell: |
                sudo mkdir -p /nfs-storage
                sudo mount {{nfs_source}}  /nfs-storage
      
      - name: Test for line
        shell: grep -c "nfs-storage" /etc/exports || true
        register: test_grep

      - name: Add NFS access rights for k8 cluster nodes 
        lineinfile:
          path: "/etc/exports"
          line: |
                /nfs-storage *(rw,no_subtree_check,no_root_squash)
        when: test_grep.stdout == "0"

      - name: enable nfs-server
        shell: |
               sudo systemctl enable --now nfs-server
               sudo exportfs -ar

- hosts:
  - localhost
  tasks:

     - name: change to kustomize file directory for nfs-server
       shell: |
               cd ../kustomize/nfs-provisioner
               kustomize build .   --enable-helm |kubectl apply -f -